### ISSUE TITLE
Issues with event system and multiple Diva panes on same page

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/diva.js#234]
I don't know if this is something that's going to be worked on with the work @magoni is doing now, but if not this may come back to bite us in the future:

For a specific example, when there are multiple Diva panes active simultaneously, creating a Diva object five times means that the toolbar listeners (cmd+F "settings.toolbar =" in the main file and that should get you there) are applied and added to the stack five times. This means that every time the page changes in one Diva pane, all five update; that said, this isn't a fatal/obvious error in most cases, since most of these functions just paste the current value for a specific variable into the GUI. I'm still afraid it either a) will be an issue in some case in the future or b) may lead to performance issues in some cases.

#210 and https://github.com/DDMAL/diva.js/commit/6f080df1705ea0abb58a2a19c11ae6b2929c1a81 are very relevant to this, but I don't know a way to patch that back into the functions that were already created and, in retrospect, I'm not sure that implementation was best. A brief overview of what that does is, if you click on a Diva pane, it knows to register that as THE currently active Diva (by setting settings.isDivaActive = true) that all keyboard input events (notably arrow key scrolling) should affect.

I can think of two options, given what we currently have, to fix this issue:

1) Re-implement the Events object as a part of the Diva instance itself, which will be a pain to do but is likely the safest option in the end (and is what I did with the MEI Editor).

2) Change my multiDivaController to respond to mouse position as well (without clicks), and add a "isDivaActive" check to the necessary functions inside Diva. This may lead to issues when events/changes are entirely programmatic and aren't affected by user input.

There's also a possibility that this is not enough of an issue to worry about. 

What do you guys think?

**Comment by ahwitz** [comment]
You're comfortable with a global events system now so we're going to do it.

The revision is to have all events be settings.id+"PageDidLoad" or something of that ilk so we can contact multiple diva objects.

Can also have something to send "PageDidLoad" to all diva objects; this will be prototyped by Hankinson shortly

**Comment by magoni** [comment]
This has not been implemented yet. @ahankinson are Diva instance prefixes to event names something I should add for 4.1?

**Comment by ahwitz** [comment]
FWIW, the activeDivaController object is a bit more stable now, and I never ended up implementing 2) in my original issue report.

**Comment by magoni** [comment]
Following our brief discussion yesterday, here's the current state of Events and multiple Diva instances:

When `publish` is called, i.e.
```
diva.Events.publish('Event', [args], self);
```
all subscribed functions are called with the `this` object specified by `self`. However, they also have access to `settings` in the private namespace because they are contained in a closure (the Diva instance in which they were defined.)

So if I call `publish` within Diva instance 1, it executes the functions that were subscribed by `1-diva` and by `2-diva`, in their respective different contexts, but with the same `this`. This hasn't been a problem because we don't use `this` in private functions, but the decoupling seems strange to me.

Some possible implementations/solutions:

1) When we publish an event within a Diva instance, only execute those subscribers that were subscribed to within specified Diva instances:
```
diva.Events.publish('Event', [args], this, [instanceID]);
```

This is dangerous and bad because if there are functions subscribed to Diva that we don't know about (i.e. written in the context of new plugins or external applications), they will no longer be triggered. Generally, we want to emit events/state changes that can be 'picked up' by any function.

or

2) When we subscribe to an event, optionally only subscribe it to events published within the specified Diva instances:
```
diva.Events.subscribe('Event', callback, [instanceID]);
```

If the instanceID argument is omitted, the function will be triggered regardless of which instance the publish call is emitted from.

The second way makes more sense to me.

**Comment by wabain** [comment]
IMO something like (2) sounds good from a user perspective

An alternative to `diva.Events.subscribe('Event', callback, [instanceID])` would be to have a subscribe method on the Diva instance which only subscribes to that instance, as well as having diva.Events for subscribing to all instances.

**Comment by ahankinson** [comment]
I'm OK with #2 as well.

**Comment by magoni** [comment]
I could use some feedback on my implementation. Here's a structure for the Events cache used by `publish` and `subscribe` that I think makes sense:

```
cache = {
    'VisiblePageDidChange': [
        externalApp.changeFolio
    ],
    '1-diva-': {
        'ModeDidSwitch': [
            settings.toolbar.switchMode
        ],
        'ViewDidSwitch': [
            settings.toolbar.switchView, 
            settings.toolbar.displayViewMenu
        ]
    }
}
```

Functions subscribed with an instance argument get stored in the cache under that instance, and functions subscribed without an instance argument ('global' subscribers) will get fired for all instances.  When `publish` is called, it first executes global subscribers and then instance subscribers.

With this structure in mind, an implementation of `publish` and `subscribe` is here: https://github.com/DDMAL/diva.js/commit/07204245c4ce804f9db8bdb397fd5164caa67aae
Let me know if you have ideas for optimizations or refactoring.

**Comment by magoni** [comment]
I'm working on unsubscribe functions now. So far, here's how I'm implementing them:

```
diva.Events.unsubscribe(handle, completely)
```
If the subscriber was initially subscribed to a particular instance, it is unsubscribed from that particular instance. If it was subscribed globally, it is unsubscribed globally.

`completely` unsubscribes every subscriber from a given topic, for an instance if the function `unsubscribe` called on was subscribed to an instance, and globally if it was subscribed globally.

```
diva.Events.unsubscribeAll(scope)
```
Removes all subscribers (global and instance) by default. If scope argument provided, unsubscribes from the given instance or global if 'global' supplied.

**Comment by magoni** [comment]
Documented and merged into develop, closing.

**Comment by ahankinson** [comment]
:cake: :fireworks: :shipit:
