### ISSUE TITLE
Plugins only enabled in minified js

### ISSUE THREAD

**Issue by stenskjaer** [DDMAL/diva.js#266]
I had problems enabling any of the included plugins, but noticed that they work as soon as I use the minified js rather than the readable js. 
Is that a feature?
Using latest (3.2.0) releast from the download page.

Awesome project by the way. Thanks for all your work.

**Comment by magoni** [comment]
The readable JS does not include the plugins. If you use the readable JS, you must individually embed what you need from the `/js/plugins` folder. (`utils.js` must also be included separately.) For example:
```javascript
<script src="/js/utils.js" type="text/javascript"></script>
<script src="/js/diva.js" type="text/javascript"></script>
<script src="/js/plugins/highlight.js" type="text/javascript"></script>
<script src="/js/plugins/download.js" type="text/javascript"></script>
```

Let me know if you have any more questions!

**Comment by stenskjaer** [comment]
All right. 
Then yes, maybe that should be said in the documentation, because I looked in vain (maybe it's there, I just didn't see it). 
Just curious: What is the reason for this difference? Are there other differences between the two files that would be nice to know about?

**Comment by magoni** [comment]
The readable JS is meant to be used only in development (because it is uncompiled and unoptimized), and to facilitate easier development, plugins are written in separate files. So the reason for the difference is that we compile the plugins and utilities into `diva.min.js` (using Google's Closure Compiler), while the `diva.js` file just has the core source code. Other than the inclusion of `utils.js` and anything in the plugins folder (which you can see in the source code), the files are identical.

**Comment by stenskjaer** [comment]
That's sensible. Thanks!
