### ISSUE TITLE
Support IIIF image 'supports' property

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#297]
Not exactly sure what's up with it, but some Wellcome Library MSS, including [this one](http://wellcomelibrary.org/iiif/b21307362/manifest), seem to only allow image requests for fixed, specified sizes. This will presumably have to wait for continuous zooming, but it would be nice to support it.

**Comment by magoni** [comment]
The allowed sizes appear in the `thumbnail` block in each canvas. [Here](https://groups.google.com/forum/#!msg/iiif-discuss/tFKyYkFjgYU/2AT0BJ7nDAAJ) is the reasoning behind Wellcome Library's fixed thumbnail sizes.

In the future maybe we could only make requests at the specified thumbnail sizes for grid view to speed things up. To do this, Diva should support the `supports` property in the [image information](http://iiif.io/api/image/2.0/#image-information), so I edited the issue title.

**Comment by jeromepl** [comment]
The problem with Wellcome library's manifest seems to be that the width and height of an image is much smaller than the width and height of the canvas in which it is.
Setting the width and height of the image to be identical to the canvas size like this seems to work:
![screen shot 2016-08-18 at 3 17 42 pm](https://cloud.githubusercontent.com/assets/7671307/17787423/15d78228-6557-11e6-8644-b50adb214434.png)

Also, there seems to be nothing else than a URL in the 'thumbnail' field now.
I thus think this is something that should be addressed by the library and not by us.
I also do not think that querying the info.json for each image would be a good thing, since that would add a lot of requests and slow down the entire process.
Closing this issue for now.

**Comment by ahankinson** [comment]
OK please make a note of this on the google docs for IIIF problems

**Comment by jeromepl** [comment]
Just added it, but this is not a library that serves anything related to music.
