### ISSUE TITLE
IIIF demo is not loading?

### ISSUE THREAD

**Issue by lpugin** [DDMAL/diva.js#316]
For both https://ddmal.github.io/diva.js/try/demo/iiif-external.html and https://ddmal.github.io/diva.js/try/iiif-highlight-pages/ with Chrome

**Comment by ahankinson** [comment]
I have fixed the first one, and patched up the second.

The issue is loading mixed HTTP and HTTPS content. Although we're serving the Diva page over https, very few libraries are serving their manifests over https, so we're getting blocked when trying to mix the two.

**Comment by lpugin** [comment]
In the first demo, changing the ms seems always to show the first (Harvard) one. Or is this what you mean by first one?

**Comment by ahankinson** [comment]
The "second" is the one where you can switch manifests. The only manifest that is available over https is the Harvard one, so when you switch there's likely an error in the console saying that it's been blocked.

**Comment by wabain** [comment]
There was a post about this recently on [iiif-discuss](https://groups.google.com/forum/#!searchin/iiif-discuss/https/iiif-discuss/S3pWvo15Kms/D2nci8TlAwAJ) with no real silver bullets. I think the options here are to redirect HTTPS traffic to HTTP for the IIIF-external demo, or to replace the HTTP-only resources with ones served over HTTPS. In addition to the Harvard MS, we could have something from e-codices and probably at least one other source.

I'll also open an issue about error handling, since the user-facing behaviour here doesn't seem very good.

**Comment by wabain** [comment]
I've added a warning message prompting the user to switch to HTTP. I think that should be good for now.
