### ISSUE TITLE
Handle cross-domain request errors

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#318]
The error handler on jQuery's `ajax` method doesn't fire on cross-domain manifest requests (I think because it's handled as JSONP?) so we need to find some other way to handle those. This is follow-up from #316.

**Comment by ahankinson** [comment]
JSONP defines a callback in the request, doesn't it? Can the error handling be done in the callback?

**Comment by wabain** [comment]
I'm sure there's some way around it. I haven't looked into it beyond verifying that the handler wasn't called and checking the jQuery docs.

**Comment by jeromepl** [comment]
How can I reproduce this? Loading anything from localhost seems to work, so I am guessing I need to test this on a server. Does this mean I need to upgrade the http://ddmal.github.io/diva.js/try/demo/ page to Diva 5.0 and from there debug the issue? If that is the case, who do I need to talk to in order to get access to that server?

**Comment by EricHanLiu** [comment]
No longer using jQuery's `ajax` for requests, and I believe the cross domain errors are fired properly now
