### ISSUE TITLE
Verify expected values for horizontal offset tests

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#331]
I found a class of test cases where the expected value was being computed conditionally and always coming out to zero. I dropped the dead branches for now, but I'm not sure zero is really the right value.

**Comment by jeromepl** [comment]
Turns out zero is really the correct expected value. The reason is that the document width fits entirely in the viewport width, and thus no scroll is needed to see parts of the document (horizontally).
These tests should therefore use a higher zoom level because that would allow scrolling. However, I tried using a zoom level with the code that was removed in ef5163de275e3eec8019ea171d72f2acdc9b96be without any success. There seems to be something off in the calculations, and my knowledge of the internal positioning system is currently too limited to address this.

**Comment by EricHanLiu** [comment]
Tests use the default zoom level and all get 0 for the horizontal scroll level since (as mentioned above) the scrollbar isn't required.

Will add some tests that test horizontal scroll at a higher zoom level, moving this to issue #422 for code coverage
