### ISSUE TITLE
Fix the gotoPreviousHighlight/gotoNextHighlight methods in highlight plugin

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#340]
I believe these are the only parts of the plugin code (apart from pagealias) to still be broken by the refactoring.

**Comment by jeromepl** [comment]
Leaving this here as reference and so that I can address this tomorrow:

`gotoNextHighlight` and `gotoPreviousHighlight` both seem to work fine, except in the event that a document is 'paged' but that one of the page is not. In the highlighting demo (using Beromunster), gotoNextHighlight thus crashes at the fourth call, when trying to `gotoPageIndex(4)`, because the 5th page of Beromunster is tagged `viewingHint: "non-paged"`.

Now this is not really a issue caused by the highlight plugin. Anything that tries to run `gotoPageIndex(4)` will crash (**only** if in book view). The reason is in book-layout's `getGroupings` method, there is code that ignores pages that are tagged as 'non-paged':
```
if (manifest.paged && !page.paged)
            return;
```
This means the page won't be added to the `pageGroups` and thus won't be part of the "searchable" pages if I can say.

Now I do not know why this was implemented that way, and I am unsure if I should simply remove this condition or not. Can anyone help me figure this out?

**Comment by wabain** [comment]
The Presentation API states (if I recall correctly) that canvases with a
viewing hint of non-paged within a manifest with a viewing hint of paged
should not be displayed in a paged interface.

**Comment by jeromepl** [comment]
Yes, you are right, thank you for that information. This means that there are 'holes' in the page indices when in book layout. How should this be addresses. I played a bit with the code and added an extra check that the page is paged in `ImageManifest.isPageValid`, and that solved a few things, like the highlight plugin, but when a user enters manually a page index in the toolbar, he can get a message saying `Invalid page number` for a page that is clearly within the range of the indices.
Is that the desired behaviour?

**Comment by jeromepl** [comment]
@ahankinson I would like your opinion on this. If we keep those holes, then we need to handle the case mentioned above where a user enters an invalid index in the input field of the toolbar. Also, the `isPageValid` method should be made public.

**Comment by wabain** [comment]
For what it's worth, what I usually got diva to do internally was have a method generate an array of relevant values and then iterate over that, rather than having to have validity checks within every loop.

**Comment by ahankinson** [comment]
There are a couple options here. The first is just to ignore them. 

The second, and probably most desirable option, is to indicate that there is a non-paged option available through an icon or something. The cases where this might happen might be where a particular detail of the page is captured (say, a detailed photograph of the gutter, or a fold-out page). 

I don't think this is the same thing as multiple images per canvas, though.

**Comment by jeromepl** [comment]
How about this:
We ignore them for the Diva 5.0 release, but include a button that toggles whether 'non-paged' pages are visible or not in Diva 6.0.  We should put more thought into what the interface is going to look like and, more importantly, how the page indices are going to be affected. If some piece of code holds a page index to refer to a page in a document, how can this index be mapped to a new one that takes into consideration the newly added 'non-paged' pages?

I think all this discussion should go in a separate issue if we are to do this in 6.0 only.

**Comment by jeromepl** [comment]
Summary of a discussion I had with @ahankinson :

This will be split into two different issues.
1 - The input field in the toolbar should be used as a search box to find matching page label names.
2 - An icon needs to be shown next to a page that has a 'non-paged' neighbour. When clicked, the 'non-paged' neighbour should be displayed.
