### ISSUE TITLE
Highlights do not scroll properly with the page

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#354]
The highlights move around on the page as it scrolls in the `iiif-highlight.html` demo. Kinda cool, but probably not what we're looking for.

**Comment by jeromepl** [comment]
Are you talking about a delay between the canvas update and the overlay update, or about highlights messing up when scrolling? I can see the delay of the first option I mentioned, and I can try to optimize it, but I can't guarantee it will follow perfectly the canvas when scrolling.
The reason is that the canvas rendering is much faster than the DOM update that is required to move the overlay in the scrolling direction.

**Comment by ahankinson** [comment]
How much work would it be to convert the highlights to canvas too?

**Comment by jeromepl** [comment]
Actually quite a lot of work.

The current implementation renders `div`s on an overlay over the canvas. To display the 'tag' attached to a highlight, it relies on the `mouseenter` event on those `div`s in the overlay. Furthermore, the 'tag' (or 'name') of the highlight is stored in the new HTML5 `data-` attributes, in this case `data-name`.
If we move to a canvas implementation, the `mouseenter` needs to be replaced by a `mousemove` and check if the position of the mouse intersects any of the bounding boxes of the highlights. If it does, the name can then be retrieved from the same object that contains the bounding box.

...or, we keep the same overlay, but make it completely transparent and render just the red highlights on the canvas. I will look into that.

**Comment by ahankinson** [comment]
It can be low priority and even punted to 5.X or 6.0. It will need to be addressed sometime, though.

**Comment by EricHanLiu** [comment]
Seems this has been fixed, don't see the problem in 
https://ddmal.github.io/diva.js/try/highlight.html

Closing
