### ISSUE TITLE
Draw Partial Tiles on Viewer Edges

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/diva.js#358]
See [this FIXME](https://github.com/DDMAL/diva.js/blob/develop/source/js/composite-image.js#L85)

I think it is better to render only visible parts of images for the simple reason that Internet Explorer throws an `IndexSizeError` every time Diva tries to render something outside of the canvas bounds. This error doesn't seem to alter execution of any code, but is annoying to see.

This is open for discussion.

Refs #355

**Comment by EricHanLiu** [comment]
Seems this is related to (and could be fixed by changing) the `viewportMargin` setting (see [line 98](https://github.com/DDMAL/diva.js/blob/filter_queue/source/js/diva.js#L98)), however we should leave it to render the non-visible tiles since it speeds up loading - changing it to 0 would fix the error in IE, but isn't a desirable option
