### ISSUE TITLE
Add filter composition queue to manipulation plugin

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#375]
A filter composition queue system has been started, but not finished, in the manipulation plugin. This will let the user apply multiple filters to an image, and it will preserve order and extent of the filter.

**Comment by ahankinson** [comment]
The idea of the composition queue is that different filter effects can be applied in sequence. For example, if you adjusted the brightness and then the contrast, you would want the second operation to take place on the modified (brightness-adjusted) pixels, and not on the original image. The queue would track each filter and its order of application.

There are a number of filters pre-built in `source/js/plugins/_filters.js`. Each one is implemented with a "public" and "private" implementation, where the public function exposes a standard API to which the private implementation of the function is applied to the incoming data. Some filters, like the threshold filter, take a parameter for adjusting thresholding.

The `manipulation.js` file contains some old testing code, but also code to keep for the plugin. I would suggest working on the composition queue functionality (started in _filter.js), and then figure out what needs to be removed in the `manipulation.js` plugin file.

**Comment by EricHanLiu** [comment]
See the [filter queue branch](https://github.com/DDMAL/diva.js/tree/filter_queue) for progress on this feature

**Comment by EricHanLiu** [comment]
Works with applying distinct filters on top of one another. Stores all the filter data (image data, filter function, adjust) in the queue, which is an array of objects.

Changing an existing filter still needs to be implemented. Thinking of doing something like
1. Reapply the filter with the new adjust
2. Reapply all the filters that come after it in the queue

**Comment by EricHanLiu** [comment]
Should be implemented properly now, though there is some variance because the order in which the user enters filters **does** matter 
> max vibrance then invert =/= invert then max vibrance

and the way it's done now is it just reapplies all the filters that come after in the queue, where the queue is ordered based on the first time the filter was used.

For example, if the user applies:
1. invert
2. vibrance
3. invert again
4. contrast
5. vibrance again

Then the queue will be 
1. invert
2. vibrance
3. contrast

Perhaps I need to move the filters to the end of the queue if they're reused, so that they can be reapplied in the proper order if something near the start of the queue is redone? Though I'm not sure if this will affect the way the filters are applied right now

**Comment by EricHanLiu** [comment]
I think the last variance was because I had a typo with not assigning the new `adjust` parameter to the filter object.

Should work now!

**Comment by EricHanLiu** [comment]
This has been implemented
