### ISSUE TITLE
Book view and page indices

### ISSUE THREAD

**Issue by wagnerflo** [DDMAL/diva.js#404]
Currently it seems impossible to know which two pages are visible in book layout if the viewer is sufficiently zoomed out that both fit at the same time. `VisiblePageDidChange` always returns the first/left-hand page and I'm not sure if/how I could detect that both pages are visible at the same time.

Any ideas?

**Comment by ahankinson** [comment]
@EricHanLiu I think this can be fixed and we can improve the 'Visible Pages' functionality to help with knowing what page labels to show.

Currently the 'visible pages' only shows one of the page indices. We should be able to have an array of which pages are currently visible in the viewport.

 - If a user zooms in on a book-layout page so that only one page is visible, then we should only have one page 'result'
 - If a user has the grid-layout turned on, we should show a range from the first to last pages that are visible. 

We can start here: 
https://github.com/DDMAL/diva.js/blob/develop/source/js/diva.js#L1262-L1272

Perhaps have a look at the `renderedPages` array on the renderer? https://github.com/DDMAL/diva.js/blob/develop/source/js/renderer.js#L536-L539

**Comment by EricHanLiu** [comment]
This is trickier than I first thought it would be - it's easy to get the true rendered pages (by temporarily setting the `intersectionTolerance` to 0), but difficult to catch the event publish properly without attaching a scroll listener (which seems like overkill).

What I mean is the user can be in book view with 4 pages visible, so the visible pages will be those four. The user can then scroll down to only see two pages without triggering a `VisiblePageDidChange` event, yet the visible pages calculated will still be those 4. 

Might need to attach a scroll listener since the `VisiblePageDidChange` event doesn't always trigger when needed.

**Comment by EricHanLiu** [comment]
This addresses a bug within Diva where it's difficult to know exactly which pages are in the viewport because the `viewerState.currentPageIndex` should realistically return the set of indices that are visible. This would allow the `VisiblePageDidChange` event to fire any time a page leaves or joins the viewport (leaves/joins the array).

`setCurrentPage(pageIndex)` in `viewer-core.js` will have to be rewritten to `setCurrentPages` and take in a number of possible page array configurations (for document/book/grid view), and I guess somehow center the viewer within that array? 

Likely a lot of changes will have to be made for how the rendering is done

**Comment by EricHanLiu** [comment]
See PR #435, the "Visible Page" feature now correctly returns all the visible pages in the viewport and all dependent features have been adjusted to account for this change, now determined correctly by their region (see issue #436 for this bug).

Will remove the `activePageIndex` attribute to remove Diva's dependence on a single page index having priority (used in certain methods such as `getCurrentCanvas()`, which will need to be changed to return a set of values corresponding to the array of visible pages).

**Comment by EricHanLiu** [comment]
All the bugs related to this issue have been fixed, closing.
