### ISSUE TITLE
Port Unit Tests to new framework

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#409]
Diva 6 is a pretty big rewrite to ES6. In the process, a new unit testing framework was put into place, but the unit tests themselves were not ported.

The old unit tests are here:

https://github.com/DDMAL/diva.js/tree/master/tests/unit

The new testing harness was set up, but the tests themselves were not ported:

https://github.com/DDMAL/diva.js/blob/develop/test/diva_test.js

The tasks are:

- [x] review the old unit tests and determine which ones are appropriate to port
- [x] port these tests to the new framework
- [x] fill in any gaps with new unit tests

**Comment by EricHanLiu** [comment]
Added all utils unit tests and the non-async/jquery tests

**Comment by EricHanLiu** [comment]
Unit tests that require a Diva instance (happen to be async and use lots of jQuery) are failing. Instances of Diva can be properly created using `npm canvas` and `isomorphic-fetch` instead of `whatwg-fetch`. 

Here is a breakdown of what's happening in the `hashparams.js` ported from Diva5 (and adapted to be compatible with Diva6, `mocha`, and `chai`):
1. I create a diva instance
2. diva subscribes to the `ViewerDidLoad` event. 
3. once the diva instance is completely initialized, the `viewer-core` will publish the `ViewerDidLoad` event, with argument `settings` (which up until here is valid and defined)
4. the subscription event's callback gets called. here, settings is all of a sudden undefined (`{}`)
5. here, another function is called (`onReadyCallback`, the specific test) with arguments settings (and `scroll` which is used by some tests). 
6. inside this new function, the actual assertions are made. however, they all fail since `settings` somehow refers to all the possible `chai` assertions instead of the viewer settings
7. this test never finishes, and `timeout`s (I've changed it to longer to make sure it wasn't a `timeout` issue). throws a `UnhandledPromiseRejectionWarning` because the test fails

[Here is a gist of the code](https://gist.github.com/EricHanLiu/91441375c8fba7670613b8583dd462a1)

Not sure why the `viewer-core settings` become undefined once passed to the callback, perhaps an issue with how the event stores the arguments?

**Comment by EricHanLiu** [comment]
Turns out it was the javascript `.call()` function's arguments including `assert` and not `this` in the right order. Now the settings are defined properly, yet for some reason `inGrid` is false.

**Comment by EricHanLiu** [comment]
The majority (80%?) of the old unit tests have been ported and adapted to work with the new testing harness. None of the rendering tests have been implemented yet, but the ones that require a DOM of some sort have using `jsdom`. 

I'm putting this issue aside for now until I figure out how to setup `Karma` with a headless browser (probably `mocha-headless-chrome`) and ES6

**Comment by EricHanLiu** [comment]
Setup `karma` properly within the new testing framework, working on migrating the rest of the `jQuery` implemented unit tests. 

An issue with the hash parameter tests not working with the page number 
eg. `#p=5`, diva should load on page 5

**Comment by EricHanLiu** [comment]
Added and adapted all Diva5 unit tests except for `navigation.js` (to be done later).

Still have the page hash parameter issue **within the unit tests**. Setting the page with `goToPageByIndex()` works properly.

**Comment by EricHanLiu** [comment]
All the tests have been ported! There are 97 total, a few were disabled because they tested features that were deprecated in Diva6. 

If there are new features of Diva in v6 that need to be tested, it'd help if you could point them out to me @ahankinson 

Otherwise, this issue should be closed soon

**Comment by EricHanLiu** [comment]
Readded the tests for tool-control settings and page-label checks, based on the reimplemented features (see issue #421)
