### ISSUE TITLE
Forbidden 403 when accessing http://127.0.0.1/fcgi-bin/IIPImageServer.fcgi

### ISSUE THREAD

**Issue by kev1807** [DDMAL/diva.js#420]
Hi there, 

I am currently working on my PhD - an digital edition in the making and I aim for diva.js as my facsimile-viewer. 
However, I set up an Apache-Server in "C:\" and followed the tutorial linked somewhere here
(http://iipimage.sourceforge.net/2008/06/how-to-install-iipimageserver-on-your-windows-computer-using-apache-22-in-11-easy-steps/) 
And adapted the paths that are mentioned to match mine (C:\Apache24/fcgi-bin/ ) 
then I ran http://127.0.0.1/fcgi-bin/IIPImageServer.fcgi and hit a dead end: 
![grafik](https://user-images.githubusercontent.com/15955790/43523900-10de7cb2-959e-11e8-805b-33fcc5af0396.png)

my httpd.conf: https://pastebin.com/cmw0pm0Z

my httpd-iimage.conf: https://pastebin.com/8tzNsw0A

Installed Software: 
Win 10, 64 bit Home Edition
Apache 2.4 (installed by apachelounge) 
exist-db (running on localhost:8080) , maybe that's the issue? However I need apache and exist-db since I aim to run an xml-db (hopefully on the infrastructure of my alma mater) which links to the images. 

I am posting this here and on the Open Discussion on Source Forge (where the main action of IIPImageServer seems to be going on), since this is closely related.
Maybe someone ran into similar issues and can provide any help

I hope you can (and will) help me! 
Best wishes and thanks in advance! 
Kevin

**Comment by ahankinson** [comment]
Hi Kevin, I'm afraid I don't know that much about running IIP on Windows. I would check that all your paths are correctly referenced.

I also note that the version of IIP referenced on that page is very old, since this article is from 2008 (gosh, 10 years!)

If you can get IIP to run, I would suggest trying another IIIF-compatible image server, like Cantaloupe: https://medusa-project.github.io/cantaloupe/

**Comment by EricHanLiu** [comment]
Inactive, closing
