### ISSUE TITLE
Make main image centered and zoomable (Manipulation Plugin)

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#440]
The primary image should be centred on the screen and take up as much area as possible. (fit the image to the screen)

It should also be zoomable with a slider. Users can grab and pan the image if it goes out of the screen.

**Comment by EricHanLiu** [comment]
Made main image centered. will do zoomable

**Comment by EricHanLiu** [comment]
Image is zoomable with slider, though this works off the full sized image so the resolution is bad when you zoom in. I'm not sure how to fetch the smaller regioned images (that are higher resolution) while still loading the entire image so that it can be panned.

Also, adding the `dragscroll` to the `manipulation-main-area` div doesn't make it drag scrollable for some reason.

**Comment by EricHanLiu** [comment]
Added drag scroll when zoomed. Might not be the best implementation (binding the reset function to the window).

Image can be zoomed up to 3x the original size, though it uses the `full` image from the IIIF API request spec, so the resolution doesn't adjust dynamically like it does with the tile fetching for Diva.

**Comment by EricHanLiu** [comment]
issue now is zooming in, applying filter, zooming out. this seemingly causes the context scale to not update

**Comment by EricHanLiu** [comment]
fix is harder than I thought, issues with keeping track of the right imageData when zooming and applying filters (and the right scale)

**Comment by EricHanLiu** [comment]
Fixed! Filters now persist through zooms

This had to be fixed by triggering the `handleZoom()` function after applying a filter to 'reset' it to the current zoom level, since the filters are all applied on the original image data (otherwise lower zoom level image datas are lost).
